#!/usr/bin/env bash
# =============================================================================
# generate-auth-keys.sh
#
# Generates the RSA-2048 key pair required by the Auth Service and writes
# them to stagepass-infrastructure/.env.auth as base64-encoded DER bytes.
#
# Run once before `docker compose up` for the first time.
# The .env.auth file is gitignored — never commit it.
#
# WHY DER+base64, not PEM?
#   The Auth Service reads the private key as a DER-encoded PKCS#8 byte array
#   and loads it with KeyFactory. PEM has a header/footer and line breaks that
#   complicate environment variable injection. DER+base64 is a single string.
#
# USAGE:
#   cd ~/stagepass/stagepass-infrastructure
#   bash scripts/generate-auth-keys.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$INFRA_DIR/.env.auth"
TEMP_DIR="$(mktemp -d)"

cleanup() { rm -rf "$TEMP_DIR"; }
trap cleanup EXIT

echo "Generating RSA-2048 key pair..."

# Generate RSA private key in PEM format
openssl genrsa -out "$TEMP_DIR/private.pem" 2048 2>/dev/null

# Convert private key to PKCS#8 DER format, then base64 (no line wrapping)
PRIVATE_KEY_B64=$(
  openssl pkcs8 -topk8 -inform PEM -outform DER \
    -in "$TEMP_DIR/private.pem" -nocrypt \
    | base64 -w 0
)

# Extract RSA public key in DER format, then base64
PUBLIC_KEY_B64=$(
  openssl rsa -in "$TEMP_DIR/private.pem" -pubout -outform DER 2>/dev/null \
    | base64 -w 0
)

# Write the .env.auth file
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/generate-auth-keys.sh
# DO NOT COMMIT THIS FILE — it contains the RSA private key.
# Regenerate with: bash scripts/generate-auth-keys.sh
AUTH_RSA_PRIVATE_KEY=${PRIVATE_KEY_B64}
AUTH_RSA_PUBLIC_KEY=${PUBLIC_KEY_B64}
EOF

echo "✅ Keys written to: $ENV_FILE"
echo ""
echo "Next step:"
echo "  cd docker/compose && docker compose up --build"
